import { Lead, Company, Contact, AgentStatus, Workflow, Campaign, Deal, NotificationItem, UserProfile } from "@/types";

export const mockCurrentUser: UserProfile = {
  id: "usr-01",
  name: "Alex Sterling",
  email: "alex.sterling@enterprise-ai.io",
  role: "Chief Revenue Officer & Admin",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
  organization: "Nexus AI Growth Corp",
  plan: "Enterprise Platinum AI",
  twoFactorEnabled: true,
};

export const mockLeads: Lead[] = [
  {
    id: "lead-101",
    name: "Sarah Jenkins",
    title: "VP of Enterprise Engineering",
    company: "Stripe Tech Solutions",
    email: "s.jenkins@stripe-demo.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    score: 96,
    status: "Hot",
    source: "LinkedIn Crawler Agent",
    owner: "Alex Sterling",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    industry: "Fintech & Payments",
    companySize: "1,000 - 5,000",
    annualRevenue: "$250M",
    techStack: ["React", "Node.js", "PostgreSQL", "AWS", "Kafka", "Kubernetes"],
    createdAt: "2026-07-28T10:30:00Z",
    updatedAt: "2026-07-31T14:20:00Z",
    tags: ["High ICP", "Decision Maker", "Q3 Budget Approved"],
    notesCount: 4,
    activityCount: 12,
  },
  {
    id: "lead-102",
    name: "Marcus Vance",
    title: "Head of Growth & Operations",
    company: "DataVanguard Inc",
    email: "m.vance@datavanguard.io",
    phone: "+1 (555) 876-5432",
    location: "New York, NY",
    score: 89,
    status: "Hot",
    source: "Search Discovery Agent",
    owner: "Elena Rostova",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    industry: "Data Analytics SaaS",
    companySize: "250 - 500",
    annualRevenue: "$45M",
    techStack: ["Next.js", "Python", "Snowflake", "dbt", "TailwindCSS"],
    createdAt: "2026-07-29T11:15:00Z",
    updatedAt: "2026-07-31T12:00:00Z",
    tags: ["Fast Growth", "Hiring Spree"],
    notesCount: 2,
    activityCount: 8,
  },
  {
    id: "lead-103",
    name: "Dr. Aris Thorne",
    title: "Chief Information Officer",
    company: "BioHealth Global",
    email: "athorne@biohealth-global.com",
    phone: "+1 (555) 345-6789",
    location: "Boston, MA",
    score: 74,
    status: "Warm",
    source: "Web Scraper",
    owner: "David Chen",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    industry: "Healthcare Technology",
    companySize: "5,000+",
    annualRevenue: "$1.2B",
    techStack: ["Java", "Oracle", "Azure", "Docker"],
    createdAt: "2026-07-25T08:45:00Z",
    updatedAt: "2026-07-30T16:10:00Z",
    tags: ["Enterprise", "Compliance Focus"],
    notesCount: 6,
    activityCount: 15,
  },
  {
    id: "lead-104",
    name: "Emily Watson",
    title: "Director of Product Marketing",
    company: "CloudSphere AI",
    email: "e.watson@cloudsphere.ai",
    phone: "+1 (555) 901-2345",
    location: "Austin, TX",
    score: 82,
    status: "Warm",
    source: "HubSpot Import",
    owner: "Alex Sterling",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
    industry: "Cloud & Infrastructure",
    companySize: "100 - 250",
    annualRevenue: "$20M",
    techStack: ["React", "TypeScript", "GCP", "HubSpot"],
    createdAt: "2026-07-26T14:20:00Z",
    updatedAt: "2026-07-31T09:00:00Z",
    tags: ["Warm Lead", "Email Opened 3x"],
    notesCount: 1,
    activityCount: 5,
  },
  {
    id: "lead-105",
    name: "Jameson Blake",
    title: "Chief Technology Officer",
    company: "FinNexus Labs",
    email: "j.blake@finnexus.co",
    phone: "+1 (555) 432-1098",
    location: "Chicago, IL",
    score: 62,
    status: "Cold",
    source: "Directory Extractor",
    owner: "Elena Rostova",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
    industry: "Financial Services",
    companySize: "50 - 100",
    annualRevenue: "$12M",
    techStack: ["Go", "Kubernetes", "Redis", "PostgreSQL"],
    createdAt: "2026-07-20T09:00:00Z",
    updatedAt: "2026-07-24T11:30:00Z",
    tags: ["Cold Outreach", "Followup Pending"],
    notesCount: 0,
    activityCount: 2,
  },
];

export const mockCompanies: Company[] = [
  {
    id: "comp-1",
    name: "Stripe Tech Solutions",
    domain: "stripe-demo.com",
    logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80",
    industry: "Fintech Infrastructure",
    size: "1,000 - 5,000 Employees",
    revenue: "$250,000,000",
    location: "San Francisco, California, USA",
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "Kafka", "AWS", "Datadog"],
    description: "Next-generation developer-first payment and financial infrastructure provider.",
    founded: 2018,
    linkedin: "https://linkedin.com/company/stripe-tech",
    twitter: "https://twitter.com/stripetech",
    employeeCount: 3200,
    leadCount: 8,
    score: 98,
  },
  {
    id: "comp-2",
    name: "DataVanguard Inc",
    domain: "datavanguard.io",
    logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80",
    industry: "Enterprise AI & Analytics",
    size: "250 - 500 Employees",
    revenue: "$45,000,000",
    location: "New York, NY, USA",
    techStack: ["Python", "PyTorch", "Snowflake", "FastAPI", "React", "Docker"],
    description: "Automated real-time business intelligence and predictive modeling platform for Fortune 500.",
    founded: 2021,
    linkedin: "https://linkedin.com/company/datavanguard",
    twitter: "https://twitter.com/datavanguard",
    employeeCount: 420,
    leadCount: 5,
    score: 92,
  },
  {
    id: "comp-3",
    name: "BioHealth Global",
    domain: "biohealth-global.com",
    logo: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=120&q=80",
    industry: "Healthcare SaaS",
    size: "5,000+ Employees",
    revenue: "$1,200,000,000",
    location: "Boston, MA, USA",
    techStack: ["Java", "Spring Boot", "Oracle Cloud", "Kubernetes", "Angular"],
    description: "Global healthcare logistics and clinical trial data management software platform.",
    founded: 2010,
    linkedin: "https://linkedin.com/company/biohealth",
    twitter: "https://twitter.com/biohealth",
    employeeCount: 6500,
    leadCount: 12,
    score: 86,
  },
];

export const mockContacts: Contact[] = [
  {
    id: "cnt-1",
    name: "Sarah Jenkins",
    title: "VP of Enterprise Engineering",
    companyId: "comp-1",
    companyName: "Stripe Tech Solutions",
    email: "s.jenkins@stripe-demo.com",
    phone: "+1 (555) 234-5678",
    linkedin: "https://linkedin.com/in/sarahjenkins-tech",
    status: "Verified",
    lastContacted: "2026-07-31T14:20:00Z",
  },
  {
    id: "cnt-2",
    name: "Marcus Vance",
    title: "Head of Growth & Operations",
    companyId: "comp-2",
    companyName: "DataVanguard Inc",
    email: "m.vance@datavanguard.io",
    phone: "+1 (555) 876-5432",
    linkedin: "https://linkedin.com/in/marcusvance",
    status: "Verified",
    lastContacted: "2026-07-30T11:00:00Z",
  },
];

export const mockAgents: AgentStatus[] = [
  {
    id: "agt-planner",
    name: "Planner Agent",
    type: "Strategy & Orchestration",
    status: "active",
    description: "Decomposes lead gen goals into sub-tasks and selects target ICP search channels.",
    runningJobs: 3,
    successRate: 99.4,
    totalExecutions: 1420,
    avgLatency: "450ms",
    lastActive: "Just now",
    config: { model: "gpt-4o", temperature: 0.2, concurrency: 5 },
    logs: [
      { timestamp: "12:44:01", level: "info", message: "Generated target strategy for Fintech ICP search batch #412" },
      { timestamp: "12:43:15", level: "info", message: "Dispatched tasks to Crawler & Search agents" },
    ],
  },
  {
    id: "agt-search",
    name: "Search Discovery Agent",
    type: "Lead Discovery",
    status: "running",
    description: "Scans Google, Bing, LinkedIn, and GitHub for companies matching ICP criteria.",
    runningJobs: 8,
    successRate: 98.1,
    totalExecutions: 8900,
    avgLatency: "1.2s",
    lastActive: "Just now",
    config: { model: "gpt-4o-mini", temperature: 0.4, concurrency: 12 },
    logs: [
      { timestamp: "12:44:10", level: "info", message: "Discovered 45 new target companies in San Francisco tech hub" },
      { timestamp: "12:44:05", level: "info", message: "Parsing web search response stream" },
    ],
  },
  {
    id: "agt-crawler",
    name: "Web Crawler Agent",
    type: "Scraping & DOM Parsing",
    status: "running",
    description: "Executes headless Playwright browsers to capture DOM, tech stack, and contact pages.",
    runningJobs: 14,
    successRate: 96.8,
    totalExecutions: 12400,
    avgLatency: "2.8s",
    lastActive: "1 min ago",
    config: { model: "custom-puppeteer-v2", temperature: 0.0, concurrency: 20 },
    logs: [
      { timestamp: "12:43:50", level: "info", message: "Successfully extracted footer links and about page from stripe-demo.com" },
    ],
  },
  {
    id: "agt-extractor",
    name: "Structured Extractor Agent",
    type: "Information Extraction",
    status: "active",
    description: "Converts raw unstructured HTML and text into JSON lead schemas.",
    runningJobs: 2,
    successRate: 99.1,
    totalExecutions: 9450,
    avgLatency: "820ms",
    lastActive: "Just now",
    config: { model: "gpt-4o", temperature: 0.1, concurrency: 10 },
    logs: [
      { timestamp: "12:44:02", level: "info", message: "Extracted 12 decision-maker names and emails from raw DOM tree" },
    ],
  },
  {
    id: "agt-enrichment",
    name: "Company & Contact Enrichment Agent",
    type: "Enrichment Engine",
    status: "active",
    description: "Cross-references company data with Clearbit, Apollo, and social profiles.",
    runningJobs: 4,
    successRate: 97.5,
    totalExecutions: 6700,
    avgLatency: "1.5s",
    lastActive: "2 mins ago",
    config: { model: "claude-3-5-sonnet", temperature: 0.2, concurrency: 8 },
    logs: [
      { timestamp: "12:42:10", level: "info", message: "Enriched Stripe Tech Solutions with funding & annual revenue data" },
    ],
  },
  {
    id: "agt-verifier",
    name: "Email & Phone Verifier Agent",
    type: "Verification & Deliverability",
    status: "active",
    description: "Performs real-time MX record checks, SMTP handshakes, and phone validation.",
    runningJobs: 6,
    successRate: 99.8,
    totalExecutions: 15200,
    avgLatency: "310ms",
    lastActive: "Just now",
    config: { model: "rule-engine-v1", temperature: 0.0, concurrency: 30 },
    logs: [
      { timestamp: "12:44:00", level: "info", message: "Verified s.jenkins@stripe-demo.com -> High Deliverability (Score: 99%)" },
    ],
  },
  {
    id: "agt-scoring",
    name: "ICP Lead Scoring Agent",
    type: "Predictive Qualification",
    status: "active",
    description: "Scores leads from 0-100 based on company size, revenue, tech stack, and intent signals.",
    runningJobs: 1,
    successRate: 100.0,
    totalExecutions: 11000,
    avgLatency: "150ms",
    lastActive: "Just now",
    config: { model: "custom-random-forest", temperature: 0.1, concurrency: 15 },
    logs: [
      { timestamp: "12:44:05", level: "info", message: "Assigned lead score 96/100 (Hot) to Sarah Jenkins" },
    ],
  },
  {
    id: "agt-outreach",
    name: "Hyper-Personalized Outreach Agent",
    type: "Messaging & Copywriting",
    status: "active",
    description: "Generates custom 1-on-1 cold email copy referencing prospect news and tech stack.",
    runningJobs: 5,
    successRate: 98.9,
    totalExecutions: 4300,
    avgLatency: "1.1s",
    lastActive: "3 mins ago",
    config: { model: "gpt-4o", temperature: 0.7, concurrency: 5 },
    logs: [
      { timestamp: "12:41:00", level: "info", message: "Drafted email sequence tailored to Stripe Tech's recent AWS migration" },
    ],
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-101",
    name: "Enterprise Fintech Lead Auto-Discovery & Enrichment",
    description: "Automatically search for VP & C-level executives in Fintech, verify email deliverability, score, and push to HubSpot CRM.",
    status: "active",
    triggersCount: 3,
    totalRuns: 1420,
    successRate: 98.9,
    lastRun: "5 mins ago",
    nodes: [
      { id: "n1", type: "trigger", label: "Cron Schedule (Every 6h)", description: "Runs search query for Fintech ICP", iconName: "Clock", status: "success" },
      { id: "n2", type: "agent", label: "Search Discovery Agent", description: "Scans web & social profiles", iconName: "Search", status: "success" },
      { id: "n3", type: "agent", label: "Web Crawler & Extractor", description: "Parses DOM & extracts emails", iconName: "Globe", status: "active" },
      { id: "n4", type: "condition", label: "Filter: Score > 80", description: "Only continue if ICP score >= 80", iconName: "Filter", status: "idle" },
      { id: "n5", type: "action", label: "HubSpot CRM Push", description: "Create lead & deal in HubSpot", iconName: "Database", status: "idle" },
    ],
  },
  {
    id: "wf-102",
    name: "High-Intent AI Startup Outreach Sequence",
    description: "Triggers hyper-personalized email outreach sequence when a target AI startup posts a new engineering job opening.",
    status: "active",
    triggersCount: 1,
    totalRuns: 890,
    successRate: 97.4,
    lastRun: "12 mins ago",
    nodes: [
      { id: "n10", type: "trigger", label: "Job Board Webhook", description: "New AI engineer job post", iconName: "Zap", status: "success" },
      { id: "n11", type: "agent", label: "Outreach Copy Agent", description: "Generates custom email draft", iconName: "Mail", status: "active" },
      { id: "n12", type: "action", label: "Send Grid Outreach", description: "Send Step 1 Cold Email", iconName: "Send", status: "idle" },
    ],
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "cmp-1",
    name: "Q3 Enterprise Fintech VP Engineering Sequence",
    status: "Active",
    totalLeads: 450,
    sentCount: 380,
    openRate: 68.4,
    clickRate: 34.2,
    replyRate: 18.5,
    schedule: "Mon - Fri @ 9:00 AM PST",
    createdAt: "2026-07-15T08:00:00Z",
  },
  {
    id: "cmp-2",
    name: "AI & ML Founder Personalized Outreach",
    status: "Active",
    totalLeads: 220,
    sentCount: 210,
    openRate: 74.1,
    clickRate: 41.0,
    replyRate: 24.8,
    schedule: "Mon - Thu @ 10:30 AM EST",
    createdAt: "2026-07-20T10:00:00Z",
  },
  {
    id: "cmp-3",
    name: "Healthcare Tech CIO Decision Makers",
    status: "Draft",
    totalLeads: 180,
    sentCount: 0,
    openRate: 0,
    clickRate: 0,
    replyRate: 0,
    schedule: "Scheduled for Aug 5",
    createdAt: "2026-07-30T14:00:00Z",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "dl-1",
    title: "Stripe Tech - Enterprise AI License",
    company: "Stripe Tech Solutions",
    contact: "Sarah Jenkins",
    value: 120000,
    stage: "Proposal",
    probability: 80,
    expectedClose: "2026-08-25",
    owner: "Alex Sterling",
  },
  {
    id: "dl-2",
    title: "DataVanguard - Growth Tier Package",
    company: "DataVanguard Inc",
    contact: "Marcus Vance",
    value: 45000,
    stage: "Negotiation",
    probability: 90,
    expectedClose: "2026-08-15",
    owner: "Elena Rostova",
  },
  {
    id: "dl-3",
    title: "BioHealth Global - Multi-Year Pilot",
    company: "BioHealth Global",
    contact: "Dr. Aris Thorne",
    value: 280000,
    stage: "Qualified",
    probability: 50,
    expectedClose: "2026-09-30",
    owner: "David Chen",
  },
  {
    id: "dl-4",
    title: "CloudSphere AI - Starter Automation",
    company: "CloudSphere AI",
    contact: "Emily Watson",
    value: 24000,
    stage: "New",
    probability: 30,
    expectedClose: "2026-08-30",
    owner: "Alex Sterling",
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Hot Lead Alert! 🚀",
    message: "Sarah Jenkins (VP of Eng at Stripe Tech) opened your email outreach for the 3rd time.",
    timestamp: "5 mins ago",
    read: false,
    type: "lead",
  },
  {
    id: "notif-2",
    title: "AI Search Discovery Complete",
    message: "Search Agent discovered 45 new qualified leads in the Fintech sector.",
    timestamp: "18 mins ago",
    read: false,
    type: "agent",
  },
  {
    id: "notif-3",
    title: "HubSpot CRM Sync Succeeded",
    message: "Successfully synchronized 14 leads and 3 deal proposals to HubSpot.",
    timestamp: "1 hour ago",
    read: true,
    type: "system",
  },
];

export const mockAnalyticsData = {
  monthlyGrowth: [
    { month: "Jan", leads: 420, conversion: 12.4, revenue: 48000 },
    { month: "Feb", leads: 680, conversion: 14.2, revenue: 64000 },
    { month: "Mar", leads: 950, conversion: 16.8, revenue: 92000 },
    { month: "Apr", leads: 1240, conversion: 18.5, revenue: 128000 },
    { month: "May", leads: 1650, conversion: 21.0, revenue: 175000 },
    { month: "Jun", leads: 2100, conversion: 23.4, revenue: 230000 },
    { month: "Jul", leads: 2840, conversion: 25.8, revenue: 310000 },
  ],
  leadSources: [
    { name: "LinkedIn Discovery Agent", value: 42, color: "#6366f1" },
    { name: "Web Crawler Engine", value: 28, color: "#8b5cf6" },
    { name: "GitHub Tech Scraper", value: 16, color: "#06b6d4" },
    { name: "HubSpot / Salesforce Sync", value: 14, color: "#10b981" },
  ],
  industryDistribution: [
    { name: "Fintech & Payments", percentage: 38 },
    { name: "Enterprise AI & SaaS", percentage: 29 },
    { name: "Healthcare Tech", percentage: 18 },
    { name: "Cloud & DevTools", percentage: 15 },
  ],
};
